/*
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.xbase.lib.util.ReflectExtensions
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import thymio_DSL.ThymioDSL
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.xtext.project.tdsl.generator.TDslGenerator

@ExtendWith(InjectionExtension)
@InjectWith(TDslInjectorProvider)
class TDslCodeGenTest {
	@Inject extension CompilationTestHelper
	@Inject extension ReflectExtensions
	
	/** 
	@Test
	def void testDSLCodeCompilesToExpectedOutput() {
		'''->On clap do:
		- play sound sound1
		If front middle horizontal sensor detecting proximity:
		- drive backward
		End if
		'''.assertCompilesTo()
	}*/

}
