/*
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TDslStandaloneSetup extends TDslStandaloneSetupGenerated {

	public static void doSetup() {
		new TDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
