/*
 * generated by Xtext 2.34.0.M2
 */
package org.xtext.project.tdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTDslScopeProvider extends DelegatingScopeProvider {
}
