/**
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl.generator;

import thymio_DSL.ArithmeticExpression;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class TDslInterpreter {
  public Integer interpret(final ArithmeticExpression e) {
    Integer _xblockexpression = null;
    {
      final Integer left = e.getLeft();
      final Integer right = e.getRight();
      Integer _switchResult = null;
      String _operator = e.getOperator();
      if (_operator != null) {
        switch (_operator) {
          case "+":
            _switchResult = Integer.valueOf(((left).intValue() + (right).intValue()));
            break;
          case "-":
            _switchResult = Integer.valueOf(((left).intValue() - (right).intValue()));
            break;
          case "*":
            _switchResult = Integer.valueOf(((left).intValue() * (right).intValue()));
            break;
          case "/":
            _switchResult = Integer.valueOf(((left).intValue() / (right).intValue()));
            break;
          case "mod":
            _switchResult = Integer.valueOf(((left).intValue() % (right).intValue()));
            break;
          default:
            _switchResult = left;
            break;
        }
      } else {
        _switchResult = left;
      }
      _xblockexpression = _switchResult;
    }
    return _xblockexpression;
  }
}
