/*
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TDslUiModule extends AbstractTDslUiModule {

	public TDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
