/*
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.project.tdsl.TDslRuntimeModule;
import org.xtext.project.tdsl.TDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TDslIdeSetup extends TDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TDslRuntimeModule(), new TDslIdeModule()));
	}
	
}
