/**
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl.tests;

import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(TDslInjectorProvider.class)
@SuppressWarnings("all")
public class TDslCodeGenTest {
}
