/*
 * generated by Xtext 2.34.0
 */
package org.xtext.project.tdsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.project.tdsl.ui.internal.TdslActivator;

public class TDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TdslActivator.getInstance().getInjector("org.xtext.project.tdsl.TDsl");
	}

}
