/*
 * generated by Xtext 2.34.0.M2
 */
package org.xtext.project.tdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.project.tdsl.parser.antlr.internal.InternalTDslParser;
import org.xtext.project.tdsl.services.TDslGrammarAccess;

public class TDslParser extends AbstractAntlrParser {

	@Inject
	private TDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTDslParser createParser(XtextTokenStream stream) {
		return new InternalTDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ThymioDSL";
	}

	public TDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
