/*
 * generated by Xtext 2.34.0.M2
 */
package org.xtext.project.tdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.project.tdsl.ui.internal.TdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TdslActivator activator = TdslActivator.getInstance();
		return activator != null ? activator.getInjector(TdslActivator.ORG_XTEXT_PROJECT_TDSL_TDSL) : null;
	}

}
